### ISSUE TITLE
Extensão parou de funcionar

### ISSUE THREAD

**Issue by Enrico712** [luiz-lp/crpiframeplayer#3]
Opa tudo tranquilo? Eu fiz um vídeo em Dezembro do ano passado ensinando a arrumar o iFrame Player de vocês (não sei se é só um criador), quando também parou de funcionar na ocasião, e de ontem pra hoje parou de novo, e por isso o povo com abstinência de anime já tá reclamando kkkkkk. Então, quando arrumarem ou criarem uma nova avisa por favor? E sem pressão, até pq vcs já ajudaram gente pra caramba tlgd, sou muito grato pelos vários animes que pude ver com a extensão de vocês, sou grato mesmo, vocês são fodas. Valeu pela atenção.

**Comment by luiz-lp** [comment]
infelizmente parou de funcionar e não tem previsão de volta
